language: ruby
rvm:
  - 1.9.3

env:
  - SUITE=spec
  #- SUITE=cucumber

notifications:
  recipients:
    - main@sharetribe.flowdock.com

branches:
  only:
    - develop

before_script:
  - cp config/database.example.yml config/database.yml
  - mysql -e 'create database sharetribe_test;'
  - rake db:test:load
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - bundle exec rake $SUITE

