branches:
  only:
    - master
bundler_args: --without development --path=~/.bundle
language: ruby
sudo: false
cache:
  directories:
  - ~/.bundle
  - node_modules
  - client/node_modules
rvm:
- 2.3.1
env:
  matrix:
  - SUITE="rspec"
  - SUITE="rubocop"
  - SUITE="cucumber"
  - SUITE="lint"
  global:
    - BUNDLE_ARCHIVE="travis-bundle-cache"
    - AWS_S3_REGION="us-east-1"
    - AWS_S3_BUCKET="sharetribe-travis-cache"
    - RAILS_ENV=test
    - secure: QJBiGsabtqY6qvGdrYoCJtSCOl53jt1dPTYG4Md++icBK4llEzRsXYoNKJdBG9Q6p3vmR/Yw76Ph2dX1lh5GeDE3aPJ1iWNSrUYDoURV/LeTNZR8bGEncJp961qYPWGoKv5t4NlgehJzwpTHIIC3ToRT5RlkZYaxTUNxvbAqj70=

    # Braintree sandbox credentials
    - braintree_environment: sandbox
    - secure: JKcR0dOvEzjuL9qrwmPX8E49UzLxK8PslpZR1F3/+bj/ZEB8dqI01eoAVLLB9aoy/7wBMizl1hzgdEk94OJLSiJibXugadOcECpjvbL4n2g8bntiij1HSpsTiBzTJqYrXBN9VCqCCxjvVNsseX4KWfyfWdKNKHX9+1eWAl6gZG8=
    - secure: X1DiDlQ+HFY8ICLwPD+sw0d1zhxoIPFDvL0WTugRzTcQlTDt+tdLJCsGs523YAp3ci/9kEPDRXlQNTN5l0PZp6S1c1Ye8nO3mTGrlIkKnkB32Y59rpR9T980LgahL3lcod1uc3EM95lOkmvO8Ma4uMM9rWjcYxnyS9TJOXuGbqE=
    - secure: AquipD3Ru6Xyk2K/mt2jmb/kh0GiAhTpLKlOsg6EdEE4VK/JPJUdbki3K/3jfwmCXZIDVBUfKjG/jt8ui0OKGlcI0ToTu4b9U1ZJ7EuMh2MibcKWb6b5XJlfYXC34jDSM4JSOyuR0ZMi0U1hcT6CJDabs6wSGQrJFiQMRSaDyMg=
    - secure: VObS2Rnc3KgPz3uO50KiWcxXa+QXrbe0HPVVmzd5AUvJuRRvv0dPJZVrgzVLh8L1KfwFemcGz/Px9Ftt6kHqGeQktrb5QypGRgyuNJccFw0Qrqk2oTE0V8eOovixoufG9pRjPGOJMBenf6IKa3+5qBrCpCmdP2je6QHIkpbG4wk=
notifications:
  flowdock:
    # Main
    - secure: FY861NHS112q8iU/meT64mfsPSr0JDx3Q4ElLdECAx+3tm6JTlKwVk35INP/pKG9n2um2LY7olDKovCtr1/FlEg9AjmGbrNSxu2ErGmhqyihj4e2qsCKYE/KioMofw1taQlnWXlOOu7ZKu3AJvauT8C4hkMGWvLtZu2ZVxhoLRM=
    # DevTeam
    - secure: ExDcKU91PdTOeNEmO3sewSz4AIB0kdLFK18eetuQdTGgreFxOazgsg7rLdkLSk/c51dydB9BWbD6+TASk91ZIYnN7xDBYsltSw1sd8xS04KI2OxoXj/QFDJYy1wpgjyVtoNhG2iuIlpMdela4S5Q9PwOHat/Tm5771ffc0DhfXI=
    # Sharetribe.org Developers
    - secure: UzPNtuYZEjujb4KJhmCyJL5nF1UPs8Z9W1Iofo+l9d9kOTAVrCo9so/b/6CXzkabU2aJ5uPmF+sQ3w/QojaXrcpnYMfO1VRZBJtTwzJYy9Bm0uKrK0JC1BE8B4zEZV8WV8AMKi36dRGnGZd6c0AWkwt6feAKND1q5H8IAbqzDNU=
# Ensure Bundler >= 1.1, don't install rdocs, and fetch a cached bundle from S3
before_install:
- ./travis/before_install.sh
install:
- ./travis/install.sh
before_script:
- ./travis/before_script.sh
script:
- ./travis/script.sh
after_script:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bundle_cache || false'
